on: [push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    name: Generate test coverage badge
    steps:

    # Install dependencies
    - name: Install dependencies
      run: |
        npm install

    # Run tests and generate coverage report
    - name: Run tests and generate coverage report
      id: coverage
      run: |
        npm run test:coverage
        COVERAGE=$(cat ./coverage/lcov.info | grep 'total' | awk '{print $3}')
        echo "##[set-output name=lines;]${COVERAGE}%"

    # Use the output from the `coverage` step
    - name: Generate the badge SVG image
      uses: emibcn/badge-action@v1
      with:
        label: 'Test coverage'
        status: ${{ steps.coverage.outputs.lines }}
        color: 'blue,555,daf'
        path: badge.svg
